/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package zeta.meta.genlexis;

public interface ParserConstants {

  int EOF = 0;
  int COMMENT = 6;
  int STRING_LITERAL = 7;
  int LITERAL = 8;
  int SEPARATOR = 9;
  int TERMINATOR = 10;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMMENT>",
    "<STRING_LITERAL>",
    "<LITERAL>",
    "\";\"",
    "\".\"",
  };

}
