#!/bin/sh

echo "visit $1 $2 $3 $4 $5" >vlog

form="(progn (require 'zeta-server) (zeta-server-visit \"$1\" $2 $3 $4 $5))"

# first try gnuclient
gnuclient -q -batch -eval "$form" 2>/dev/null
if [ $? != 0 ]
then
    # doesn't seems to run or doesn't serves. start a new xemacs
    xemacs -eval "$form" &
else
    exit 0
fi


	    
